import type { AnalysedRow, Stats, ContentType } from './types'

const LANGUAGE_NAMES: Record<string, string> = {
  EN: 'English',
  DE: 'German',
  FR: 'French',
  JP: 'Japanese',
  KR: 'Korean',
  ES: 'Spanish',
  PT: 'Portuguese',
  ID: 'Indonesian',
  VN: 'Vietnamese',
  TH: 'Thai',
  RU: 'Russian',
}

export function computeStats(rows: AnalysedRow[]): Stats {
  const stats: Stats = {
    total: rows.length,
    accepted: 0,
    wordSwap: 0,
    phraseRestructure: 0,
    fullRewrite: 0,
    contentTypes: {
      ui_text: 0,
      item_name: 0,
      skill_name: 0,
      story_dialogue: 0,
      announcement: 0,
      game_rules: 0,
      loading_screen: 0,
      general: 0,
    },
  }

  for (const row of rows) {
    switch (row.diffClass) {
      case 'accepted': stats.accepted++; break
      case 'word_swap': stats.wordSwap++; break
      case 'phrase_restructure': stats.phraseRestructure++; break
      case 'full_rewrite': stats.fullRewrite++; break
    }
    stats.contentTypes[row.contentType as ContentType]++
  }

  return stats
}

function pct(n: number, total: number): string {
  return total > 0 ? `${Math.round((n / total) * 100)}%` : '0%'
}

export function generateSkillMd(
  lang: string,
  filename: string,
  stats: Stats,
  llmAnalysis: string,
  generatedAt: Date = new Date(),
): string {
  const langName = LANGUAGE_NAMES[lang] ?? lang
  const dateStr = generatedAt.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  })

  const activeContentTypes = (Object.entries(stats.contentTypes) as [ContentType, number][])
    .filter(([, n]) => n > 0)
    .map(([type, n]) => `${type}(${n})`)
    .join(', ')

  return `---
name: Proofreading Rules — CHS → ${langName} Game Localisation
description: Auto-generated skill file derived from human proofreader corrections on AI-translated game localisation content. Inject into the proofreading agent's system prompt or knowledge base.
type: skill
generated: ${generatedAt.toISOString()}
source_file: ${filename}
language_pair: Chinese (CHS) → ${langName} (${lang})
dataset_summary: ${stats.total} rows | ${stats.accepted} accepted (${pct(stats.accepted, stats.total)}) | ${stats.wordSwap} word_swap | ${stats.phraseRestructure} phrase_restructure | ${stats.fullRewrite} full_rewrite
content_types: ${activeContentTypes}
---

# Proofreading Skill: Chinese → ${langName} Game Localisation

## Dataset Statistics

| Metric | Count | Share |
|---|---|---|
| Total rows analysed | ${stats.total} | 100% |
| Accepted (no change needed) | ${stats.accepted} | ${pct(stats.accepted, stats.total)} |
| Word swap (≤20% changed) | ${stats.wordSwap} | ${pct(stats.wordSwap, stats.total)} |
| Phrase restructure (20–60%) | ${stats.phraseRestructure} | ${pct(stats.phraseRestructure, stats.total)} |
| Full rewrite (>60%) | ${stats.fullRewrite} | ${pct(stats.fullRewrite, stats.total)} |

**Content types detected:** ${activeContentTypes || 'none'}

---

${llmAnalysis}

---

## Agent Behaviour Guidelines

1. **Use this file as your primary reference** for what good ${langName} localisation looks like in this game.
2. **Check Section 3 (Red Flags) first** — these are the highest-priority issues and must be verified on every string.
3. **Apply Section 1 rules by content type** — rules for \`story_dialogue\` do not automatically apply to \`ui_text\`, and vice versa.
4. **Do not alter patterns listed in Section 4** — these are things the AI already does correctly; changing them introduces regressions.
5. **Section 2 (Human Inconsistencies) is advisory** — be aware of both conventions but favour the more common resolution when in doubt.
6. **When in doubt, prefer the human-corrected version** — the proofreader's choices are the ground truth for this dataset.
7. **Context matters** — always read the EXTRA field for game-specific context before making a correction decision.

---

*Generated by Proofreader Skill Finder on ${dateStr}*
`
}
